version: '3'

services:
#   db:
#     image: postgres
#     restart: always
#     ports:
#       - "5432:5432"
#     env_file:
#       - db.env
#     volumes:
#       - ./postgresql:/postgresql

  mqtt:
    image: toke/mosquitto
    ports:
      - "1884:1883"

  crawler:
    build: crawler/.
    depends_on:
      - mqtt
    env_file:
      - public.env
      - private.env
    tty: true

#  api:
#     build: api
#     env_file:
#       - db.env
#       - common.env
#     depends_on:
#       - db
#       - mqtt
#
