version: '3'

services:
  mqtt:
    image: toke/mosquitto
    ports:
      - "1884:1883"

  db:
    image: postgres
    restart: always
    ports:
      - "54321:5432"
    env_file:
      - private.env
    volumes:
      - ./.postgresql:/postgresql

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.redis:/redis

  couchdb:
    image: "couchdb:2.3.1"
    hostname: couchdb.server
    ports:
      - "5984:5984"
  
  normalizer:
    restart: always
    build: normalizer/.
    depends_on:
      - mqtt
    env_file:
      - private.env
      - public.env
    tty: true

  crawler:
    restart: always
    build: crawler/.
    depends_on:
      - mqtt
    env_file:
      - private.env
      - public.env
    tty: true

  go_api:
    restart: always
    build: api/.
    env_file:
      - private.env
      - public.env
    ports:
      - "7777:8080"
    depends_on:
      - db
      - mqtt
    tty: true

  nginx:
    restart: always
    build: nginx/.
    ports:
      - 8000:80
    # links:
    #   - go_api:go_api

