FROM ubuntu:16.04

RUN apt-get update \
    && apt upgrade -y \
    && apt-get install -y \
    cron \
    build-essential \
    python3-pip \
    chromium-browser \
    nano

RUN apt-get install -y libglib2.0-0 \
    libnss3 \
    libgconf-2-4 \
    libfontconfig1

COPY . /app

RUN pip install -r /app/requirements.txt
RUN chmod -R 755 /app

WORKDIR /app

ENTRYPOINT ["/app/entrypoint.sh"]